<?php
if ( ! defined( 'ABSPATH' ) ) {
	die( 'You are not allowed to call this page directly.' );
}
class FrmStrpActionsController extends FrmTransActionsController {

	/**
	 * @since 3.1.9
	 *
	 * @var bool True if the payment is pending (a 3D Secure payment awaiting confirmation).
	 */
	private static $is_pending = false;

	/**
	 * Generate the HTML from Stripe rather than Formidable.
	 *
	 * @since 2.0
	 * @return string
	 */
	public static function show_card_callback( $callback ) {
		return 'FrmStrpActionsController::show_card';
	}

	/**
	 * Override the credit card field HTML if there is a Stripe action.
	 *
	 * @since 2.0
	 *
	 * @param array  $field
	 * @param string $field_name
	 * @param array  $atts
	 * @return void
	 */
	public static function show_card( $field, $field_name, $atts ) {
		$html_id = $atts['html_id'];

		if ( self::has_stripe_processed( $field['form_id'] ) && ! FrmFormsController::just_created_entry( $field['form_id'] ) ) {
			// Don't show the card field if the token has already been set.
			global $frm_vars;
			$has_error = isset( $frm_vars['trans_filled'] );
			if ( ! $has_error ) {
				echo '<div class="frm-card-errors frm_error" id="frm_error_' . esc_attr( $html_id ) . '" role="alert"></div>';
				return;
			}
		}

		$actions = self::get_actions_before_submit( $field['form_id'] );
		if ( empty( $actions ) && is_callable( 'FrmProCreditCardsController::show_in_form' ) ) {
			FrmProCreditCardsController::show_in_form( $field, $field_name, $atts );
		}

		$intents = array();

		include FrmStrpAppHelper::plugin_path() . '/views/payments/card-field.php';
	}

	/**
	 * Get all published payment actions with the Stripe gateway that have an amount set.
	 *
	 * @since 2.0
	 *
	 * @param string|int $form_id
	 * @return array
	 */
	public static function get_actions_before_submit( $form_id ) {
		$payment_actions = self::get_actions_for_form( $form_id );
		foreach ( $payment_actions as $k => $payment_action ) {
			$gateway   = $payment_action->post_content['gateway'];
			$is_stripe = $gateway === 'stripe' || ( is_array( $gateway ) && in_array( 'stripe', $gateway, true ) );
			if ( ! $is_stripe || empty( $payment_action->post_content['amount'] ) ) {
				unset( $payment_actions[ $k ] );
			}
		}

		/*
		if ( count( $payment_actions > 1 ) ) {
			// TODO: How to pick? Check conditional logic.
			// Create payment intent for each one.
		}
		*/
		return $payment_actions;
	}

	/**
	 * Check the Stripe link action for a form. There should only be one.
	 *
	 * @since 3.0
	 *
	 * @param string|int $form_id
	 * @return WP_Post|false
	 */
	public static function get_stripe_link_action( $form_id ) {
		$actions = self::get_actions_before_submit( $form_id );
		foreach ( $actions as $action ) {
			if ( ! empty( $action->post_content['stripe_link'] ) ) {
				return $action;
			}
		}
		return false;
	}

	/**
	 * If the names are being used on the CC fields,
	 * make sure it doesn't prevent the submission if Stripe has approved.
	 *
	 * @param array    $errors
	 * @param stdClass $field
	 * @param array    $values
	 * @return array
	 */
	public static function remove_cc_validation( $errors, $field, $values ) {
		$has_processed = self::has_stripe_processed( $field->form_id ) || isset( $_POST[ 'frmintent' . $field->form_id ] );
		if ( FrmAppHelper::is_admin_page( 'formidable-entries' ) && isset( $_GET['frm_action'] ) && 'edit' === sanitize_text_field( $_GET['frm_action'] ) ) {
			$has_processed = true;
		}

		if ( ! $has_processed ) {
			return $errors;
		}

		$field_id = isset( $field->temp_id ) ? $field->temp_id : $field->id;
		if ( isset( $errors[ 'field' . $field_id . '-cc' ] ) ) {
			unset( $errors[ 'field' . $field_id . '-cc' ] );
		}
		if ( isset( $errors[ 'field' . $field_id ] ) ) {
			unset( $errors[ 'field' . $field_id ] );
		}

		return $errors;
	}

	/**
	 * Trigger a Stripe payment after a form is submitted.
	 * This is called for both one time and recurring payments.
	 * It is also called when Stripe link is active but the Stripe payment is triggered instead with JavaScript.
	 *
	 * @param WP_Post  $action
	 * @param stdClass $entry
	 * @param stdClass $form
	 * @return array
	 */
	public static function trigger_gateway( $action, $entry, $form ) {
		$response = array(
			'success'      => false,
			'run_triggers' => false,
			'show_errors'  => true,
		);
		$atts     = compact( 'action', 'entry', 'form' );

		$amount = self::prepare_amount( $action->post_content['amount'], $atts );
		if ( empty( $amount ) || $amount == 000 ) {
			$response['error'] = __( 'Please specify an amount for the payment', 'formidable' );
			return $response;
		}

		$is_stripe_link = ! empty( $action->post_content['stripe_link'] );

		// retrieve the token generated by stripe.js
		if ( ! $is_stripe_link && ! self::has_stripe_processed( $form->id ) ) {
			$response['error'] = __( 'The Stripe Token is missing.', 'formidable-stripe' );
			return $response;
		}

		if ( ! self::stripe_is_configured() ) {
			$response['error'] = __( 'There was a problem communicating with Stripe. Please try again.', 'formidable' );
			return $response;
		}

		$customer_id = false;
		if ( $is_stripe_link ) {
			if ( ! empty( $_POST[ 'frmintent' . $form->id ] ) && is_array( $_POST[ 'frmintent' . $form->id ] ) ) {
				$setup_intent_ids = array_filter(
					$_POST[ 'frmintent' . $form->id ],
					function ( $intent_id ) {
						return 0 === strpos( $intent_id, 'seti_' );
					}
				);
				if ( $setup_intent_ids ) {
					$first_setup_intent_id = reset( $setup_intent_ids );
					$first_setup_intent_id = explode( '_secret_', $first_setup_intent_id )[0];
					$setup_intent          = FrmStrpAppHelper::call_stripe_helper_class( 'get_setup_intent', $first_setup_intent_id );
					if ( is_object( $setup_intent ) && ! empty( $setup_intent->customer ) ) {
						$customer_id = $setup_intent->customer;
					}
				}
			}
		}

		$customer = self::set_customer_with_token( $atts, $customer_id );
		if ( ! is_object( $customer ) ) {
			$response['error'] = $customer;
			return $response;
		}

		$one_time_payment_args = compact( 'customer', 'form', 'entry', 'action', 'amount' );

		if ( $is_stripe_link ) {
			if ( ! FrmStrpLinkController::create_pending_stripe_link_payment( $one_time_payment_args ) ) {
				$response['error'] = __( 'There was something wrong with the payment data.', 'formidable' );
				return $response;
			}
			$response['show_errors'] = false;
			return $response;
		}

		// attempt to charge the customer's card
		if ( 'recurring' === $action->post_content['type'] ) {
			$charge = self::trigger_recurring_payment( compact( 'customer', 'entry', 'action', 'amount' ) );
		} else {
			$charge = self::trigger_one_time_payment( $one_time_payment_args );

			if ( ! self::$is_pending ) {
				$response['run_triggers'] = true;
			}
		}

		if ( $charge === true ) {
			$response['success'] = true;
		} else {
			$response['error'] = $charge;
		}

		return $response;
	}

	/**
	 * Check if either Stripe integration is enabled.
	 *
	 * @return bool true if either Stripe Connect or the legacy integration is set up.
	 */
	private static function stripe_is_configured() {
		return FrmStrpAppHelper::call_stripe_helper_class( 'initialize_api' );
	}

	/**
	 * Check POST data to determine if a Stripe payment has been submitted.
	 * stripeToken: Set when the card will be processed after entry. May not result in successful payment.
	 * stripeMethod: The payment method has been verified.
	 * frmauth: The payment intent has been created.
	 *
	 * @since 2.0
	 *
	 * @param string|int $form_id
	 * @return bool
	 */
	private static function has_stripe_processed( $form_id ) {
		return isset( $_POST['stripeToken'] ) || isset( $_POST[ 'frmauth' . $form_id ] ) || isset( $_POST['stripeMethod'] );
	}

	/**
	 * Set a customer object to $_POST['customer'] to use later.
	 *
	 * @param array $atts
	 * @return mixed
	 */
	private static function set_customer_with_token( $atts, $customer_id = false ) {
		if ( isset( $_POST['customer'] ) ) {
			// It's an object if this isn't the first Stripe action running.
			return $_POST['customer'];
		}

		$payment_info = array(
			'user_id' => FrmTransAppHelper::get_user_id_for_current_payment(),
		);

		if ( $customer_id ) {
			$payment_info['customer_id'] = $customer_id;
		}

		if ( isset( $_POST['stripeToken'] ) ) {
			$payment_info['source'] = sanitize_text_field( $_POST['stripeToken'] );
		}

		if ( ! empty( $atts['action']->post_content['email'] ) ) {
			$payment_info['email'] = apply_filters( 'frm_content', $atts['action']->post_content['email'], $atts['form'], $atts['entry'] );
			if ( $payment_info['email'] === '[email]' ) {
				$payment_info['email'] = FrmProAppHelper::get_current_user_value( 'user_email' );
			}
		}

		self::add_customer_name( $atts, $payment_info );

		$customer          = FrmStrpAppHelper::call_stripe_helper_class( 'get_customer', $payment_info );
		$_POST['customer'] = $customer; // Set for later use.

		return $customer;
	}

	/**
	 * Set the customer name based on the mapped first and last name fields in the Stripe action.
	 *
	 * @since 2.02
	 *
	 * @param array $atts
	 * @param array $payment_info
	 * @return void
	 */
	private static function add_customer_name( $atts, &$payment_info ) {
		if ( empty( $atts['action']->post_content['billing_first_name'] ) ) {
			return;
		}

		$name = '[' . $atts['action']->post_content['billing_first_name'] . ' show="first"]';
		if ( ! empty( $atts['action']->post_content['billing_last_name'] ) ) {
			$name .= ' [' . $atts['action']->post_content['billing_last_name'] . ' show="last"]';
		}

		$payment_info['name'] = apply_filters( 'frm_content', $name, $atts['form'], $atts['entry'] );
	}

	/**
	 * Create a new Stripe subscription and a subscription and payment for the payments tables.
	 *
	 * @param array $atts Includes 'customer', 'entry', 'action', 'amount'.
	 * @return bool|string True on success, error message on failure
	 */
	private static function trigger_recurring_payment( $atts ) {
		$new_charge = array(
			'customer'         => $atts['customer']->id,
			'plan'             => FrmStrpSubscriptionHelper::get_plan_from_atts( $atts ),
			'payment_behavior' => 'allow_incomplete',
			'expand'           => array( 'latest_invoice.payment_intent' ),
			'off_session'      => true,
		);

		$trial_end = self::get_trial_end_time( $atts );
		if ( $trial_end ) {
			$new_charge['trial_end'] = $trial_end;
		}

		/**
		 * @since 3.1.9
		 *
		 * @param array $new_charge
		 * @param array $atts
		 */
		$new_charge = apply_filters( 'frm_strp_new_subscription', $new_charge, $atts );

		$charge = FrmStrpAppHelper::call_stripe_helper_class( 'create_subscription', $new_charge );
		$charge = FrmStrpSubscriptionHelper::maybe_create_missing_plan_and_create_subscription( $charge, $new_charge, $atts['action'], $atts['amount'] );

		if ( is_string( $charge ) ) {
			// String $charge values are error messages.
			return $charge;
		}

		if ( ! is_object( $charge ) ) {
			// Handle if $charge is false edge case.
			return __( 'Something went wrong when trying to create a subscription.', 'formidable' );
		}

		$atts['charge']         = FrmStrpSubscriptionHelper::prepare_charge_object_for_subscription( $charge, $atts['amount'] );
		$atts['charge']->sub_id = FrmStrpSubscriptionHelper::create_new_subscription( $atts );

		$atts['status'] = 'pending';
		self::adjust_for_free_trial( $atts );

		if ( ! empty( $charge->latest_invoice->payment_intent ) ) {
			$intent         = $charge->latest_invoice->payment_intent;
			$payment_status = $intent->status;

			if ( $charge->status === 'incomplete' ) {
				if ( in_array( $payment_status, array( 'requires_action', 'requires_source_action' ), true ) ) {
					$confirm_url = FrmStrpAuth::redirect_auth( $atts, $intent->id );
					if ( $confirm_url ) {
						$atts['meta_value'] = array( 'confirm' => $confirm_url );
					}
				} elseif ( 'requires_payment_method' === $payment_status ) {
					$payment_failure = self::subscription_payment_failed( $intent );
					if ( $payment_failure ) {
						$atts['status'] = 'failed';
						$success        = $payment_failure;
					}
					unset( $payment_failure );
				}
			}

			$atts['charge']->id = $intent->id;
		}

		self::create_new_payment( $atts );

		if ( ! isset( $success ) ) {
			$success = true;
		}

		return $success;
	}

	/**
	 * @since 3.1.4
	 *
	 * @param object $intent
	 * @return string|false
	 */
	private static function subscription_payment_failed( $intent ) {
		if ( 'card_declined' !== $intent->last_payment_error->code ) {
			return false;
		}

		$charge = reset( $intent->charges->data );
		if ( 'failed' === $charge->status ) {
			return $charge->failure_message;
		}

		return false;
	}

	/**
	 * Maybe update charge attributes for free trials.
	 *
	 * @param array $atts
	 * @return void
	 */
	private static function adjust_for_free_trial( &$atts ) {
		$trial_end = self::get_trial_end_time( $atts );
		if ( ! $trial_end ) {
			return;
		}

		$atts['charge']->amount               = 0;
		$atts['charge']->current_period_start = time();
		$atts['charge']->current_period_end   = $trial_end;
	}

	/**
	 * Get the trial period from the settings or from the connected entry.
	 *
	 * @since 1.16
	 *
	 * @param array $atts Includes 'customer', 'entry', 'action', 'amount'.
	 * @return int The timestamp when the trial should end. 0 for no trial
	 */
	public static function get_trial_end_time( $atts ) {
		$settings = $atts['action']->post_content;
		if ( ! empty( $settings['trial_interval_count'] ) ) {
			$trial = $settings['trial_interval_count'];
			if ( ! is_numeric( $trial ) ) {
				$trial = FrmTransAppHelper::process_shortcodes(
					array(
						'value' => $trial,
						'entry' => $atts['entry'],
					)
				);
			}
			if ( $trial ) {
				return strtotime( '+' . absint( $trial ) . ' days' );
			}
		}
		return 0;
	}

	/**
	 * Trigger a one time payment.
	 *
	 * @param array $atts {
	 *     @type stdClass $form
	 *     @type stdClass $entry
	 *     @type WP_Post  $action
	 *     @type string   $amount
	 *     @type object   $customer
	 * }
	 * @return string|true string on error, true on success.
	 */
	private static function trigger_one_time_payment( $atts ) {
		$new_charge = self::new_one_time_array( $atts );

		if ( FrmStrpAuth::process_payment_before() ) {
			$charge = self::capture_one_time_payment( $atts, $new_charge );
		} else {
			$charge = self::run_new_charge( $atts, $new_charge );
		}

		if ( ! is_object( $charge ) ) {
			return $charge;
		}

		self::$is_pending = false;

		if ( isset( $charge->object ) && $charge->object === 'payment_intent' ) {
			if ( $charge->status === 'succeeded' ) {
				$atts['status'] = 'complete';
			} elseif ( $charge->status === 'requires_action' || $charge->status === 'requires_source_action' ) {
				// Allow for SCA after entry.
				$confirm_url = FrmStrpAuth::redirect_auth( $atts, $charge->id );
				if ( $confirm_url ) {
					$atts['meta_value'] = array( 'confirm' => $confirm_url );
				}
				$atts['status'] = 'pending';

				self::$is_pending = true;
			} elseif ( isset( $new_charge['capture'] ) && ! $new_charge['capture'] ) {
				// Don't capture now.
				$atts['status'] = $charge->status === 'requires_capture' ? 'authorized' : 'failed';
			} else {
				// No more authentication required, so capture the charge.
				$payment        = FrmStrpAppHelper::call_stripe_helper_class( 'capture_intent', $charge->id, array( 'amount_to_capture' => $new_charge['amount'] ) );
				$atts['status'] = is_object( $payment ) && 'succeeded' === $payment->status ? 'complete' : 'failed';
			}
		} else {
			$atts['status'] = $charge->paid ? 'complete' : 'failed';
			if ( $charge->paid && ! $charge->captured ) {
				$atts['status'] = 'authorized';
			}
		}

		$atts['charge']         = new stdClass();
		$atts['charge']->id     = $charge->id;
		$atts['charge']->amount = $atts['amount'];

		self::create_new_payment( $atts );

		$success = true;
		return $success;
	}

	/**
	 * Get array data for a one time charge.
	 *
	 * @since 2.0
	 * @param array $atts
	 * @return array
	 */
	private static function new_one_time_array( $atts ) {
		$new_charge = array(
			'customer' => $atts['customer']->id,
			'currency' => $atts['action']->post_content['currency'],
			'amount'   => $atts['amount'],
		);
		if ( ! empty( $atts['action']->post_content['description'] ) ) {
			$new_charge['description'] = $atts['action']->post_content['description'];
		}

		// Include 'capture' = false to authorize only.
		if ( isset( $atts['action']->post_content['capture'] ) && $atts['action']->post_content['capture'] === 'authorize' ) {
			$new_charge['capture'] = false;
		}

		/**
		 * @param array $new_charge
		 * @param array $atts
		 */
		return apply_filters( 'frm_strp_new_charge', $new_charge, $atts );
	}

	/**
	 * Capture a one time payment.
	 *
	 * @since 2.0
	 * @param array $atts
	 * @param array $new_charge
	 * @return mixed
	 */
	private static function capture_one_time_payment( $atts, $new_charge ) {
		$intents = FrmStrpAuth::get_payment_intents( 'frmauth' . $atts['entry']->form_id );
		if ( ! $intents ) {
			return 'Payment authorization not found';
		}

		foreach ( $intents as $intent_id ) {
			$intent = FrmStrpAppHelper::call_stripe_helper_class( 'get_intent', $intent_id );
			if ( $intent->metadata->action != $atts['action']->ID ) {
				continue;
			}

			self::maybe_sync_intent( $intent, $new_charge );

			$authorize_only = isset( $new_charge['capture'] ) && ! $new_charge['capture'];
			if ( $authorize_only ) {
				// Don't continue if the payment shouldn't be captured.
				$charge           = new stdClass();
				$charge->paid     = true;
				$charge->captured = false;
				$charge->amount   = $new_charge['amount'];
				$charge->id       = $intent_id;
				return $charge;
			}

			$payment = FrmStrpAppHelper::call_stripe_helper_class( 'capture_intent', $intent_id, array( 'amount_to_capture' => $new_charge['amount'] ) );

			if ( ! is_object( $payment ) ) {
				return 'There was an issue trying to capture the payment.';
			}

			$charge = reset( $payment->charges->data );
			return $charge;
		}
	}

	/**
	 * Maybe update the payment intent with missing details like description, customer, and receipt email.
	 *
	 * @since 3.1
	 *
	 * @param object $intent
	 * @param array  $new_charge
	 * @return void
	 */
	private static function maybe_sync_intent( $intent, $new_charge ) {
		$new_charge_keys = array_keys( $new_charge );
		$new_charge_keys = array_diff( $new_charge_keys, array( 'currency', 'amount', 'capture' ) );

		$new_values = array();
		foreach ( $new_charge_keys as $key ) {
			$missing = empty( $intent->$key ) && ! empty( $new_charge[ $key ] );
			if ( $missing ) {
				$new_values[ $key ] = $new_charge[ $key ];
			}
		}

		if ( $new_values ) {
			FrmStrpAppHelper::call_stripe_helper_class( 'update_intent', $intent->id, $new_values );
		}
	}

	/**
	 * @since 2.0
	 *
	 * @param array $atts
	 * @param array $new_charge
	 * @return mixed
	 */
	private static function run_new_charge( $atts, $new_charge ) {
		if ( isset( $_POST['stripeMethod'] ) ) {
			$new_charge['payment_method'] = FrmAppHelper::get_post_param( 'stripeMethod', '', 'sanitize_text_field' );
			$new_charge['confirm']        = true;
			if ( isset( $new_charge['capture'] ) ) {
				// Allow for capture later.
				$new_charge['capture_method'] = $new_charge['capture'] ? 'automatic' : 'manual';
				unset( $new_charge['capture'] );
			}
		}
		return FrmStrpAppHelper::call_stripe_helper_class( 'run_new_charge', $new_charge );
	}

	/**
	 * Add a payment row for the payments table.
	 *
	 * @param array $atts {
	 *     @type array|object $charge
	 *     @type object       $entry
	 *     @type WP_Post      $action
	 *     @type mixed        $meta_value
	 *     @type bool|null    $test Test mode. If this is left blank, FrmStrpAppHelper::active_mode() is checked.
	 * }
	 * @return int
	 */
	private static function create_new_payment( $atts ) {
		$atts['charge'] = (object) $atts['charge'];

		$new_values = array(
			'amount'     => FrmStrpAppHelper::get_formatted_amount_for_currency( $atts['charge']->amount, $atts['action'] ),
			'status'     => $atts['status'],
			'paysys'     => 'stripe',
			'item_id'    => $atts['entry']->id,
			'action_id'  => $atts['action']->ID,
			'receipt_id' => $atts['charge']->id,
			'sub_id'     => isset( $atts['charge']->sub_id ) ? $atts['charge']->sub_id : '',
		);

		if ( isset( $atts['charge']->current_period_end ) ) {
			$new_values['begin_date']  = date( 'Y-m-d', $atts['charge']->current_period_start );
			$new_values['expire_date'] = date( 'Y-m-d', $atts['charge']->current_period_end );
		}

		if ( isset( $atts['meta_value'] ) ) {
			$new_values['meta_value'] = $atts['meta_value'];
		}

		if ( isset( $atts['test'] ) ) {
			$new_values['test'] = $atts['test'];
		} else {
			$new_values['test'] = 'test' === FrmStrpAppHelper::active_mode() ? 1 : 0;
		}

		$frm_payment = new FrmTransPayment();
		$payment_id  = $frm_payment->create( $new_values );
		return $payment_id;
	}

	/**
	 * Convert the amount from 10.00 to 1000.
	 *
	 * @param mixed $amount
	 * @param array $atts
	 * @return string
	 */
	public static function prepare_amount( $amount, $atts = array() ) {
		$amount   = parent::prepare_amount( $amount, $atts );
		$currency = self::get_currency_for_action( $atts );
		return number_format( $amount, $currency['decimals'], '', '' );
	}

	/**
	 * Add defaults for additional Stripe action options.
	 *
	 * @param array $defaults
	 * @return array
	 */
	public static function add_action_defaults( $defaults ) {
		$defaults['plan_id']     = '';
		$defaults['capture']     = '';
		$defaults['stripe_link'] = '';
		return $defaults;
	}

	/**
	 * Print additional options for Stripe action settings.
	 *
	 * @param array $atts
	 * @return void
	 */
	public static function add_action_options( $atts ) {
		$form_action    = $atts['form_action'];
		$action_control = $atts['action_control'];
		include FrmStrpAppHelper::plugin_path() . '/views/action-settings/options.php';
	}

	/**
	 * @since 3.1.7
	 *
	 * @param array   $js_vars
	 * @param WP_Post $payment_action
	 * @return array
	 */
	public static function update_payment_action_js_vars( $js_vars, $payment_action ) {
		$js_vars['layout'] = isset( $payment_action->post_content['layout'] ) ? $payment_action->post_content['layout'] : ''; /** @phpstan-ignore-line */
		return $js_vars;
	}

	/**
	 * Filter Stripe action on save.
	 *
	 * @param array $settings
	 * @param array $action
	 * @return array
	 */
	public static function before_save_settings( $settings, $action = array() ) {
		$settings['currency']    = strtolower( $settings['currency'] );
		$settings['stripe_link'] = ! empty( $settings['stripe_link'] ) ? 1 : 0;
		$settings                = self::create_plans( $settings );
		return $settings;
	}

	/**
	 * Create any required Stripe plans, used for subscriptions.
	 *
	 * @param array $settings
	 * @return array
	 */
	public static function create_plans( $settings ) {
		if ( $settings['type'] !== 'recurring' || strpos( $settings['amount'], ']' ) ) {
			// Don't create a plan for one time payments, or for actions with shortcodes in the value.
			$settings['plan_id'] = '';
			return $settings;
		}

		$plan_opts = FrmStrpSubscriptionHelper::prepare_plan_options( $settings );
		if ( $plan_opts['id'] != $settings['plan_id'] ) {
			$settings['plan_id'] = FrmStrpSubscriptionHelper::maybe_create_plan( $plan_opts );
		}

		return $settings;
	}

	/**
	 * Include settings in the plan description in order to make sure the correct plan is used.
	 *
	 * @param array $settings
	 * @return string
	 */
	public static function create_plan_id( $settings ) {
		$amount = self::prepare_amount( $settings['amount'], $settings );
		$parts  = array(
			sanitize_title_with_dashes( $settings['description'] ),
			$amount,
			$settings['interval_count'] . $settings['interval'],
			$settings['currency'],
		);
		if ( isset( $settings['trial_interval_count'] ) && '' !== $settings['trial_interval_count'] ) {
			$parts[] = $settings['trial_interval_count'];
		}
		$id = implode( '_', $parts );
		return $id;
	}

	/**
	 * If this form submits with ajax, load the scripts on the first page.
	 *
	 * @param array $params
	 * @return void
	 */
	public static function maybe_load_scripts( $params ) {
		if ( $params['form_id'] == $params['posted_form_id'] ) {
			// this form has already been posted, so we aren't on the first page
			return;
		}

		$form = FrmForm::getOne( $params['form_id'] );
		if ( $form && ! empty( $form->options['ajax_submit'] ) ) {
			$credit_card_field = FrmField::getAll(
				array(
					'fi.form_id' => $form->id,
					'type'       => 'credit_card',
				)
			);
			if ( $credit_card_field ) {
				self::load_scripts( $params );
			}
		}
	}

	/**
	 * Load front end JavaScript for a Stripe form.
	 *
	 * @param array $params {
	 *     @type mixed $form_id
	 * }
	 * @return void
	 */
	public static function load_scripts( $params ) {
		if ( FrmAppHelper::is_admin_page( 'formidable-entries' ) ) {
			return;
		}

		if ( wp_script_is( 'formidable-stripe', 'enqueued' ) ) {
			return;
		}

		$settings                = FrmStrpAppHelper::get_settings();
		$stripe_connect_is_setup = FrmStrpConnectHelper::stripe_connect_is_setup();
		$publishable             = $settings->get_active_publishable_key();

		wp_register_script( 'stripe', 'https://js.stripe.com/v3/', array(), '3.0', false );

		if ( ! empty( $params['form_id'] ) ) {
			$action_settings = self::prepare_settings_for_js( $params['form_id'] );

			$found_gateway = false;
			foreach ( $action_settings as $action ) {
				$gateways = $action['gateways'];
				if ( ! $gateways || in_array( 'stripe', (array) $gateways, true ) ) {
					$found_gateway = true;
					break;
				}
			}

			if ( ! $found_gateway ) {
				return;
			}
		} else {
			$action_settings   = array();
			$params['form_id'] = 0;
		}

		wp_enqueue_script( 'formidable-stripe', FrmStrpAppHelper::plugin_url() . '/js/frmstrp' . FrmAppHelper::js_suffix() . '.js', array( 'stripe', 'formidable' ), FrmStrpVersionCheck::get_version(), false );

		$ajax_url = admin_url( 'admin-ajax.php', is_ssl() ? 'admin' : 'http' );
		$ajax_url = apply_filters( 'frm_ajax_url', $ajax_url );

		$stripe_vars = array(
			'publishable_key'  => $publishable,
			'process'          => $settings->settings->process,
			'form_id'          => $params['form_id'],
			'nonce'            => wp_create_nonce( 'frm_strp_ajax' ),
			'root'             => esc_url_raw( rest_url() ),
			'ajax'             => esc_url_raw( $ajax_url ),
			'api_nonce'        => wp_create_nonce( 'wp_rest' ),
			'settings'         => $action_settings,
			'locale'           => self::get_locale(),
			'style'            => self::prepare_styling( $params['form_id'] ),
			'appearanceRules'  => self::get_appearance_rules( $params['form_id'] ),
		);
		if ( $stripe_connect_is_setup ) {
			$stripe_vars['account_id'] = FrmStrpConnectHelper::get_account_id();
		}
		wp_localize_script( 'formidable-stripe', 'frm_stripe_vars', $stripe_vars );
	}

	/**
	 * Get the style rules for Stripe card elements.
	 *
	 * @since 2.0
	 *
	 * @param mixed $form_id
	 * @return array
	 */
	private static function prepare_styling( $form_id ) {
		$settings = self::get_style_settings_for_form( $form_id );
		return array(
			'base' => array(
				'color'         => $settings['text_color'],
				'fontFamily'    => $settings['font'],
				'fontSize'      => $settings['field_font_size'],
				'::placeholder' => array(
					'color'     => $settings['text_color_disabled'],
				),
			),
			'invalid' => array(
				'color'     => $settings['required_color'],
				'iconColor' => $settings['required_color'],
			),
		);
	}

	/**
	 * Get and format the style settings for JavaScript to use with the prepare_styling and get_appearance_rules functions.
	 *
	 * @since 3.0
	 *
	 * @param mixed $form_id
	 * @return array
	 */
	private static function get_style_settings_for_form( $form_id ) {
		if ( ! $form_id ) {
			return array();
		}

		$style = FrmStylesController::get_form_style( $form_id );
		if ( ! $style ) {
			return array();
		}

		$settings   = FrmStylesHelper::get_settings_for_output( $style );
		$disallowed = array( ';', ':', '!important' );
		foreach ( $settings as $k => $s ) {
			if ( is_string( $s ) ) {
				$settings[ $k ] = str_replace( $disallowed, '', $s );
			}
		}

		return $settings;
	}

	/**
	 * Get the style rules for Stripe link Authentication and Payment elements.
	 * These settings get set to frm_stripe_vars.appearanceRules.
	 * They're in the format that Stripe accepts.
	 * Documentation for Appearance rules can be found at https://stripe.com/docs/elements/appearance-api?platform=web#rules
	 *
	 * @since 3.0
	 *
	 * @param mixed $form_id
	 * @return array
	 */
	private static function get_appearance_rules( $form_id ) {
		$settings = self::get_style_settings_for_form( $form_id );
		$rules    = array(
			'.Input' => array(
				'fontFamily'      => $settings['font'],
				'color'           => $settings['text_color'],
				'backgroundColor' => $settings['bg_color'],
				'padding'         => $settings['field_pad'],
				'lineHeight'      => 1.3,
				'borderColor'     => $settings['border_color'],
				'borderWidth'     => self::get_border_width( $settings ),
				'borderStyle'     => $settings['field_border_style'],
				'borderRadius'    => self::get_border_radius( $settings ),
				'fontWeight'      => $settings['field_weight'],
			),
			'.Input::placeholder' => array(
				'color' => $settings['text_color_disabled'],
			),
			'.Input:focus' => array(
				'backgroundColor' => $settings['bg_color_active'],
			),
			'.Label' => array(
				'color'        => $settings['label_color'],
				'fontSize'     => $settings['font_size'],
				'fontWeight'   => $settings['weight'],
				'padding'      => $settings['label_padding'],
				'marginBottom' => 0,
			),
			'.Error' => array(
				'color' => $settings['border_color_error'],
			),
		);

		/*
		 * Filters the appearance rules for Stripe elements.
		 *
		 * @since 3.1.7
		 *
		 * @param array $rules
		 * @param array $settings
		 */
		$rules = apply_filters( 'frm_stripe_appearance_rules', $rules, $settings );
		return $rules;
	}

	/**
	 * Get the border width for Stripe elements.
	 *
	 * @since 3.1.7
	 *
	 * @param array $settings
	 * @return string
	 */
	private static function get_border_width( $settings ) {
		if ( ! empty( $settings['field_shape_type'] ) && 'underline' === $settings['field_shape_type'] ) {
			return '0 0 ' . $settings['field_border_width'] . ' 0';
		}
		return $settings['field_border_width'];
	}

	/**
	 * Get the border radius for Stripe elements.
	 *
	 * @since 3.1.7
	 *
	 * @param array $settings
	 * @return string
	 */
	private static function get_border_radius( $settings ) {
		if ( ! empty( $settings['field_shape_type'] ) ) {
			switch ( $settings['field_shape_type'] ) {
				case 'underline':
				case 'regular':
					return '0px';
				case 'circle':
					return '30px';
			}
		}
		return $settings['border_radius'];
	}

	/**
	 * Get the language to use for Stripe elements.
	 *
	 * @since 2.0
	 * @return string
	 */
	private static function get_locale() {
		$allowed = array( 'ar', 'da', 'de', 'en', 'es', 'fi', 'fr', 'he', 'it', 'ja', 'nl', 'no', 'pl', 'ru', 'sv', 'zh' );
		$current = get_locale();
		$parts   = explode( '_', $current );
		$part    = strtolower( $parts[0] );
		return in_array( $part, $allowed, true ) ? $part : 'auto';
	}

}
